//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Dominex.DataLayer.DataSources.Game.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakePresetKingdomDataSource : FakeDataSource<Dominex.Model.Game.PresetKingdom>, Dominex.DataLayer.DataSources.Game.IPresetKingdomDataSource
{
	public FakePresetKingdomDataSource(params Dominex.Model.Game.PresetKingdom[] data)
		: this((IEnumerable<Dominex.Model.Game.PresetKingdom>)data)
	{			
	}

	public FakePresetKingdomDataSource(IEnumerable<Dominex.Model.Game.PresetKingdom> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
