//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DependencyInjection;
using Havit.Data.EntityFrameworkCore.Patterns.Infrastructure;
using Havit.Data.EntityFrameworkCore.Patterns.Repositories;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.DataSources;
using Havit.Data.Patterns.Infrastructure;
using Havit.Data.Patterns.Repositories;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace Dominex.DataLayer;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static partial class DataLayerServiceExtensions
{
	public static IServiceCollection AddDataLayerServices(this IServiceCollection services, ComponentRegistrationOptions options = null)
	{
		services.AddDataLayerCoreServices(options);
	
		AddDataSources(services);
		AddRepositories(services);
		AddDataEntries(services);
		AddEntityKeyAccessors(services);

		return services;
	}

	private static void AddDataSources(IServiceCollection services)
	{
		services.TryAddTransient<Dominex.DataLayer.DataSources.Common.IApplicationSettingsDataSource, Dominex.DataLayer.DataSources.Common.ApplicationSettingsDbDataSource>();
		services.TryAddTransient<IDataSource<Dominex.Model.Common.ApplicationSettings>, Dominex.DataLayer.DataSources.Common.ApplicationSettingsDbDataSource>();

		services.TryAddTransient<Dominex.DataLayer.DataSources.Common.ICountryDataSource, Dominex.DataLayer.DataSources.Common.CountryDbDataSource>();
		services.TryAddTransient<IDataSource<Dominex.Model.Common.Country>, Dominex.DataLayer.DataSources.Common.CountryDbDataSource>();

		services.TryAddTransient<Dominex.DataLayer.DataSources.Common.ICountryLocalizationDataSource, Dominex.DataLayer.DataSources.Common.CountryLocalizationDbDataSource>();
		services.TryAddTransient<IDataSource<Dominex.Model.Common.CountryLocalization>, Dominex.DataLayer.DataSources.Common.CountryLocalizationDbDataSource>();

		services.TryAddTransient<Dominex.DataLayer.DataSources.Game.IPresetKingdomDataSource, Dominex.DataLayer.DataSources.Game.PresetKingdomDbDataSource>();
		services.TryAddTransient<IDataSource<Dominex.Model.Game.PresetKingdom>, Dominex.DataLayer.DataSources.Game.PresetKingdomDbDataSource>();

		services.TryAddTransient<Dominex.DataLayer.DataSources.Localizations.ILanguageDataSource, Dominex.DataLayer.DataSources.Localizations.LanguageDbDataSource>();
		services.TryAddTransient<IDataSource<Dominex.Model.Localizations.Language>, Dominex.DataLayer.DataSources.Localizations.LanguageDbDataSource>();

		services.TryAddTransient<Dominex.DataLayer.DataSources.Security.IRoleDataSource, Dominex.DataLayer.DataSources.Security.RoleDbDataSource>();
		services.TryAddTransient<IDataSource<Dominex.Model.Security.Role>, Dominex.DataLayer.DataSources.Security.RoleDbDataSource>();

		services.TryAddTransient<Dominex.DataLayer.DataSources.Security.IUserDataSource, Dominex.DataLayer.DataSources.Security.UserDbDataSource>();
		services.TryAddTransient<IDataSource<Dominex.Model.Security.User>, Dominex.DataLayer.DataSources.Security.UserDbDataSource>();

	}

	private static void AddRepositories(IServiceCollection services)
	{
		services.TryAddScoped<Dominex.DataLayer.Repositories.Common.IApplicationSettingsRepository, Dominex.DataLayer.Repositories.Common.ApplicationSettingsDbRepository>();
		services.TryAddScoped<IRepository<Dominex.Model.Common.ApplicationSettings, System.Int32>>(sp => sp.GetRequiredService<Dominex.DataLayer.Repositories.Common.IApplicationSettingsRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<Dominex.Model.Common.ApplicationSettings, System.Int32>, Dominex.DataLayer.Repositories.Common.ApplicationSettingsDbRepositoryQueryProvider>();

		services.TryAddScoped<Dominex.DataLayer.Repositories.Common.ICountryRepository, Dominex.DataLayer.Repositories.Common.CountryDbRepository>();
		services.TryAddScoped<IRepository<Dominex.Model.Common.Country, System.Int32>>(sp => sp.GetRequiredService<Dominex.DataLayer.Repositories.Common.ICountryRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<Dominex.Model.Common.Country, System.Int32>, Dominex.DataLayer.Repositories.Common.CountryDbRepositoryQueryProvider>();

		services.TryAddScoped<Dominex.DataLayer.Repositories.Common.ICountryLocalizationRepository, Dominex.DataLayer.Repositories.Common.CountryLocalizationDbRepository>();
		services.TryAddScoped<IRepository<Dominex.Model.Common.CountryLocalization, System.Int32>>(sp => sp.GetRequiredService<Dominex.DataLayer.Repositories.Common.ICountryLocalizationRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<Dominex.Model.Common.CountryLocalization, System.Int32>, Dominex.DataLayer.Repositories.Common.CountryLocalizationDbRepositoryQueryProvider>();

		services.TryAddScoped<Dominex.DataLayer.Repositories.Game.IPresetKingdomRepository, Dominex.DataLayer.Repositories.Game.PresetKingdomDbRepository>();
		services.TryAddScoped<IRepository<Dominex.Model.Game.PresetKingdom, System.Int32>>(sp => sp.GetRequiredService<Dominex.DataLayer.Repositories.Game.IPresetKingdomRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<Dominex.Model.Game.PresetKingdom, System.Int32>, Dominex.DataLayer.Repositories.Game.PresetKingdomDbRepositoryQueryProvider>();

		services.TryAddScoped<Dominex.DataLayer.Repositories.Localizations.ILanguageRepository, Dominex.DataLayer.Repositories.Localizations.LanguageDbRepository>();
		services.TryAddScoped<IRepository<Dominex.Model.Localizations.Language, System.Int32>>(sp => sp.GetRequiredService<Dominex.DataLayer.Repositories.Localizations.ILanguageRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<Dominex.Model.Localizations.Language, System.Int32>, Dominex.DataLayer.Repositories.Localizations.LanguageDbRepositoryQueryProvider>();

		services.TryAddScoped<Dominex.DataLayer.Repositories.Security.IRoleRepository, Dominex.DataLayer.Repositories.Security.RoleDbRepository>();
		services.TryAddScoped<IRepository<Dominex.Model.Security.Role, System.Int32>>(sp => sp.GetRequiredService<Dominex.DataLayer.Repositories.Security.IRoleRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<Dominex.Model.Security.Role, System.Int32>, Dominex.DataLayer.Repositories.Security.RoleDbRepositoryQueryProvider>();

		services.TryAddScoped<Dominex.DataLayer.Repositories.Security.IUserRepository, Dominex.DataLayer.Repositories.Security.UserDbRepository>();
		services.TryAddScoped<IRepository<Dominex.Model.Security.User, System.Int32>>(sp => sp.GetRequiredService<Dominex.DataLayer.Repositories.Security.IUserRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<Dominex.Model.Security.User, System.Int32>, Dominex.DataLayer.Repositories.Security.UserDbRepositoryQueryProvider>();

	}

	private static void AddDataEntries(IServiceCollection services)
	{
		services.TryAddScoped<Dominex.DataLayer.DataEntries.Common.IApplicationSettingsEntries, Dominex.DataLayer.DataEntries.Common.ApplicationSettingsEntries>();

		services.TryAddScoped<Dominex.DataLayer.DataEntries.Localizations.ILanguageEntries, Dominex.DataLayer.DataEntries.Localizations.LanguageEntries>();

	}

	private static void AddEntityKeyAccessors(IServiceCollection services)
	{
		services.TryAddTransient<IEntityKeyAccessor<Dominex.Model.Common.ApplicationSettings, System.Int32>, DbEntityKeyAccessor<Dominex.Model.Common.ApplicationSettings, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<Dominex.Model.Common.Country, System.Int32>, DbEntityKeyAccessor<Dominex.Model.Common.Country, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<Dominex.Model.Common.CountryLocalization, System.Int32>, DbEntityKeyAccessor<Dominex.Model.Common.CountryLocalization, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<Dominex.Model.Game.PresetKingdom, System.Int32>, DbEntityKeyAccessor<Dominex.Model.Game.PresetKingdom, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<Dominex.Model.Localizations.Language, System.Int32>, DbEntityKeyAccessor<Dominex.Model.Localizations.Language, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<Dominex.Model.Security.Role, System.Int32>, DbEntityKeyAccessor<Dominex.Model.Security.Role, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<Dominex.Model.Security.User, System.Int32>, DbEntityKeyAccessor<Dominex.Model.Security.User, System.Int32>>();
	}
}
