//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominex.DataLayer.DataEntries.Localizations;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class LanguageEntries : Havit.Data.Patterns.DataEntries.DataEntries<Dominex.Model.Localizations.Language, System.Int32>, ILanguageEntries
{
	private Dominex.Model.Localizations.Language _czech;
	private Dominex.Model.Localizations.Language _english;

	public Dominex.Model.Localizations.Language Czech => _czech ??= GetEntry(Dominex.Model.Localizations.Language.Entry.Czech);
	public Dominex.Model.Localizations.Language English => _english ??= GetEntry(Dominex.Model.Localizations.Language.Entry.English);

	public LanguageEntries(Dominex.DataLayer.Repositories.Localizations.ILanguageRepository repository)
		: base(repository)
	{
	}
}
