<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<AssemblyName>Dominex.Web.Server</AssemblyName>
		<RootNamespace>Dominex.Web.Server</RootNamespace>
		<ImplicitUsings>true</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Infrastructure\SignalRHubs\**" />
	  <Content Remove="Infrastructure\SignalRHubs\**" />
	  <EmbeddedResource Remove="Infrastructure\SignalRHubs\**" />
	  <None Remove="Infrastructure\SignalRHubs\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire" />
		<PackageReference Include="Hangfire.Console" />
		<PackageReference Include="Havit.Blazor.Components.Web.Bootstrap" />
		<PackageReference Include="Havit.Blazor.Grpc.Server" />
		<PackageReference Include="Havit.Hangfire.Extensions" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="protobuf-net.Grpc.AspNetCore.Reflection" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Contracts\Contracts.csproj" />
		<ProjectReference Include="..\DataLayer\DataLayer.csproj" />
		<ProjectReference Include="..\DependencyInjection\DependencyInjection.csproj" />
		<ProjectReference Include="..\Facades\Facades.csproj" />
		<ProjectReference Include="..\Model\Model.csproj" />
		<ProjectReference Include="..\Primitives\Primitives.csproj" />
		<ProjectReference Include="..\Services\Services.csproj" />
		<ProjectReference Include="..\Web.Client\Web.Client.csproj" />
	</ItemGroup>

	<Target Name="TfsPublish" AfterTargets="AfterPublish" Condition="'$(PublishDirectory)' != ''">
		<ItemGroup>
			<PublishToCopy Include="obj\Release\TfsPublish\*.zip" />
		</ItemGroup>
		<Copy SourceFiles="@(PublishToCopy)" DestinationFolder="$(PublishDirectory)\Web" />
	</Target>

	<Target Name="EnsureWebJobInPackage" AfterTargets="CreateReadyToRunImages" BeforeTargets="_PrepareForReadyToRunCompilation">
		<Error Text="WebJob file Dominex.Utility.exe not found when preparing web deploy package." Condition="!Exists('..\Utility\bin\Release\net9.0\Dominex.Utility.exe')" />
		<ItemGroup>
			<!-- Vybereme soubory k publikaci. Předpokládá, že Utility je závislostí WebAPI nastavené v SLN. -->
			<WebJobFiles Include="..\Utility\bin\Release\net9.0\**" />
			<!-- Přidej soubory do ResolvedFileToPublish s nastavením cesty, kam mají být umístěny (složka pro webjoby). -->
			<ResolvedFileToPublish Include="@(WebJobFiles)">
				<RelativePath>app_data\jobs\continuous\Utility\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>
</Project>
