//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Dominex.DataLayer.DataSources.Common.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeCountryLocalizationDataSource : FakeDataSource<Dominex.Model.Common.CountryLocalization>, Dominex.DataLayer.DataSources.Common.ICountryLocalizationDataSource
{
	public FakeCountryLocalizationDataSource(params Dominex.Model.Common.CountryLocalization[] data)
		: this((IEnumerable<Dominex.Model.Common.CountryLocalization>)data)
	{			
	}

	public FakeCountryLocalizationDataSource(IEnumerable<Dominex.Model.Common.CountryLocalization> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
