//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.Patterns.Repositories;

namespace Dominex.DataLayer.Repositories.Game;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public partial interface IPresetKingdomRepository : IRepository<Dominex.Model.Game.PresetKingdom, System.Int32>
{
}
