//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.Repositories;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Microsoft.EntityFrameworkCore;
using DbContext = Havit.Data.EntityFrameworkCore.DbContext;

namespace Dominex.DataLayer.Repositories.Game;

internal class PresetKingdomDbRepositoryQueryProvider : IRepositoryQueryProvider<Dominex.Model.Game.PresetKingdom, System.Int32>
{
	private readonly Func<DbContext, System.Int32, Dominex.Model.Game.PresetKingdom> _getObjectQuery;
	private readonly Func<DbContext, System.Int32, CancellationToken, Task<Dominex.Model.Game.PresetKingdom>> _getObjectAsyncQuery;
	private readonly Func<DbContext, System.Int32[], IEnumerable<Dominex.Model.Game.PresetKingdom>> _getObjectsQuery;
	private readonly Func<DbContext, System.Int32[], IAsyncEnumerable<Dominex.Model.Game.PresetKingdom>> _getObjectsAsyncQuery;

	public PresetKingdomDbRepositoryQueryProvider()
	{
		_getObjectQuery = EF.CompileQuery((DbContext dbContext, System.Int32 id) => dbContext
			.Set<Dominex.Model.Game.PresetKingdom>()
			.TagWith("PresetKingdomDbRepository.GetObject")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32 id, CancellationToken cancellationToken) => dbContext
			.Set<Dominex.Model.Game.PresetKingdom>()
			.TagWith("PresetKingdomDbRepository.GetObjectAsync")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectsQuery = EF.CompileQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<Dominex.Model.Game.PresetKingdom>()
			.TagWith("PresetKingdomDbRepository.GetObjects")
			.Where(entity => ids.Contains(entity.Id)));

		_getObjectsAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<Dominex.Model.Game.PresetKingdom>()
			.TagWith("PresetKingdomDbRepository.GetObjectsAsync")
			.Where(entity => ids.Contains(entity.Id)));
	}

	public Func<DbContext, System.Int32, Dominex.Model.Game.PresetKingdom> GetGetObjectQuery() => _getObjectQuery;
	public Func<DbContext, System.Int32, CancellationToken, Task<Dominex.Model.Game.PresetKingdom>> GetGetObjectAsyncQuery() => _getObjectAsyncQuery;
	public Func<DbContext, System.Int32[], IEnumerable<Dominex.Model.Game.PresetKingdom>> GetGetObjectsQuery() => _getObjectsQuery;
	public Func<DbContext, System.Int32[], IAsyncEnumerable<Dominex.Model.Game.PresetKingdom>> GetGetObjectsAsyncQuery() => _getObjectsAsyncQuery;
}
