namespace Dominex.Contracts.Game;

// todo do jiných souboru (nebo do třídy choice) uvidime
// todo tento enum je možná zbytečný 
public enum ChoiceType
{
	Buy,
	Play,
	SpyDiscard,
	MilitiaDiscard,
	RemodelTrash,
	ChapelTrash,
	BureaucratPutOnTop,
	CellarDiscard,
	ChancellorDiscard,
	LibrarySkip,
	ThiefChoose,
	ThiefSteal,
	ThroneRoomPlay,
	MineTrash,
	Gain,
	MoatDefend,
	GameEnd,
	BaronDiscard,
	MoneylenderTrash,
	CourtyardPutOnTop,
	MasqueradePass,
	MasqueradeTrash,
	MinionDiscard,
	TorturerChoose,
	TorturerDiscard,
	TradingPostTrash,
	SecretChamberPutOnDeck,
	SecretChamberDiscard,
	DiplomatDiscard,
	LurkerChoose,
	LurkerTrash,
	LurkerGain,
	MillDiscard,
	ReplaceTrash,
	CourtierReveal,
	CourtierChooseBenefits,
	PawnChooseBenefits,
	StewardTrash,
	StewardChooseBenefits,
	UpgradeTrash,
	SecretPassageChooseCard,
	BanditTrash,
	ArtisanPutOnTop,
	HarbingerPutOnTop,
	PoacherDiscard,
	SentryTrash,
	SentryDiscard,
	VassalPlay,
}
