<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<AssemblyName>Dominex.DataLayer</AssemblyName>
		<RootNamespace>Dominex.DataLayer</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Havit.Data.EntityFrameworkCore.Patterns" />
		<PackageReference Include="Havit.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Havit.Extensions.DependencyInjection.SourceGenerators">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Contracts\Contracts.csproj" />
		<ProjectReference Include="..\Entity\Entity.csproj" />
		<ProjectReference Include="..\Model\Model.csproj" />
		<ProjectReference Include="..\Primitives\Primitives.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="_generated\DataEntries\Game\" />
	  <Folder Include="_generated\DataEntries\Localizations\" />
	  <Folder Include="_generated\DataEntries\Security\" />
	  <Folder Include="_generated\DataSources\Common\Fakes\" />
	  <Folder Include="_generated\DataSources\Game\Fakes\" />
	  <Folder Include="_generated\DataSources\Localizations\Fakes\" />
	  <Folder Include="_generated\DataSources\Security\Fakes\" />
	  <Folder Include="_generated\Repositories\Localizations\" />
	  <Folder Include="_generated\Repositories\Security\" />
	</ItemGroup>

</Project>
