<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<AssemblyName>Dominex.Web.Client</AssemblyName>
		<RootNamespace>Dominex.Web.Client</RootNamespace>
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
		<ImplicitUsings>true</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<TrimmerRootDescriptor Include="TrimmerRootDescriptor.xml" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Resources\Model\**" />
	  <Content Remove="Resources\Model\**" />
	  <EmbeddedResource Remove="Resources\Model\**" />
	  <None Remove="Resources\Model\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Pages\Errors\GenericError.razor" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BlazorApplicationInsights" />
		<PackageReference Include="Blazored.FluentValidation" />
		<PackageReference Include="Blazored.LocalStorage" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Havit.Blazor.Components.Web.Bootstrap" />
		<PackageReference Include="Havit.Blazor.Grpc.Client" />
		<PackageReference Include="Havit.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Havit.SourceGenerators.StrongApiStringLocalizers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Havit.Extensions.DependencyInjection.SourceGenerators">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Connections" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Contracts\Contracts.csproj" />
		<ProjectReference Include="..\Facades\Facades.csproj" />
		<ProjectReference Include="..\Primitives\Primitives.csproj" />
		<ProjectReference Include="..\Resources\Resources.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Navigation.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Navigation.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Pages\Admin\AdminIndex.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>AdminIndex.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Pages\Errors\GenericError.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>GenericError.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Navigation.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Navigation.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\Pages\Admin\AdminIndex.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>AdminIndex.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\Pages\Errors\GenericError.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>GenericError.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
