//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominex.DataLayer.DataEntries.Security;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class RoleEntries : Havit.Data.Patterns.DataEntries.DataEntries<Dominex.Model.Security.Role>, IRoleEntries 
{
	private Dominex.Model.Security.Role systemAdministrator;
	private Dominex.Model.Security.Role userSettingsAdministrator;

	public Dominex.Model.Security.Role SystemAdministrator => systemAdministrator ??= GetEntry(Dominex.Model.Security.Role.Entry.SystemAdministrator);
	public Dominex.Model.Security.Role UserSettingsAdministrator => userSettingsAdministrator ??= GetEntry(Dominex.Model.Security.Role.Entry.UserSettingsAdministrator);

	public RoleEntries(Dominex.DataLayer.Repositories.Security.IRoleRepository repository)
		: base(repository)
	{
	}
}
